### ISSUE TITLE
Get polluted location from API

### ISSUE THREAD

**Issue by BenasB** [vu-vibedosa/apsitvarkom-fe#17]
## Description

Right now, we [fake the polluted location data](https://github.com/vu-vibedosa/apsitvarkom-fe/blob/dev/src/App.tsx#L8). It is time to actually retrieve the data by using [`getAllPollutedLocations`](https://github.com/vu-vibedosa/apsitvarkom-fe/blob/dev/src/backEndClient.ts#L9).

## Steps to take

1. In `src/App.tsx` instead of faking the data, use `getAllPollutedLocations` from `src/backEndClient.ts`:
    1. Refer to [`Example` component](https://github.com/vu-vibedosa/apsitvarkom-fe/blob/dev/src/components/Example.tsx#L11) as an example . You will need `useState` and `useEffect` hooks for this.
    2. Think about what happens if back end is not reachable (display error? show 0 cards? etc.) and what is displayed if the request is slow ([you can simulate this](https://helpdeskgeek.com/networking/simulate-slow-internet-connection-testing/))

## Acceptance criteria

1. Card components rendered in `src/App.tsx` are now using real data coming in from back end API instead of fake objects.

**Comment by 6ar8nas** [comment]
Personally wasn't familiar with the slow internet connection simulation part. Sick
